# This file is part of the ProVANT simulator project. Licensed under the terms of the MIT open source license. More
# details at https://github.com/Guiraffo/ProVANT-Simulator/blob/master/LICENSE.md

controller_joint_names: ['', 'rotR', 'Hr', 'rotL', 'Hl', 'Ar', 'Al', 'Rr', 'Rl', ]
